#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_gdscript = env_modules.Clone()
env_gdscript.disable_warnings()
thirdparty_obj = []

thirdparty_dir = "#thirdparty/"

thirdparty_sources = [
    "asmjit/core/archtraits.cpp",
    "asmjit/core/assembler.cpp",
    "asmjit/core/builder.cpp",
    "asmjit/core/codeholder.cpp",
    "asmjit/core/codewriter.cpp",
    "asmjit/core/compiler.cpp",
    "asmjit/core/constpool.cpp",
    "asmjit/core/cpuinfo.cpp",
    "asmjit/core/emithelper.cpp",
    "asmjit/core/emitter.cpp",
    "asmjit/core/emitterutils.cpp",
    "asmjit/core/environment.cpp",
    "asmjit/core/errorhandler.cpp",
    "asmjit/core/formatter.cpp",
    "asmjit/core/func.cpp",
    "asmjit/core/funcargscontext.cpp",
    "asmjit/core/globals.cpp",
    "asmjit/core/inst.cpp",
    "asmjit/core/instdb.cpp",
    "asmjit/core/jitallocator.cpp",
    "asmjit/core/jitruntime.cpp",
    "asmjit/core/logger.cpp",
    "asmjit/core/operand.cpp",
    "asmjit/core/osutils.cpp",
    "asmjit/core/ralocal.cpp",
    "asmjit/core/rapass.cpp",
    "asmjit/core/rastack.cpp",
    "asmjit/core/string.cpp",
    "asmjit/core/target.cpp",
    "asmjit/core/type.cpp",
    "asmjit/core/virtmem.cpp",

    "asmjit/support/arena.cpp",
    "asmjit/support/arenabitset.cpp",
    "asmjit/support/arenahash.cpp",
    "asmjit/support/arenalist.cpp",
    "asmjit/support/arenatree.cpp",
    "asmjit/support/arenavector.cpp",
    "asmjit/support/support.cpp",

    "asmjit/arm/armformatter.cpp",
    "asmjit/arm/a64assembler.cpp",
    "asmjit/arm/a64builder.cpp",
    "asmjit/arm/a64compiler.cpp",
    "asmjit/arm/a64emithelper.cpp",
    "asmjit/arm/a64formatter.cpp",
    "asmjit/arm/a64func.cpp",
    "asmjit/arm/a64instapi.cpp",
    "asmjit/arm/a64instdb.cpp",
    "asmjit/arm/a64operand.cpp",
    "asmjit/arm/a64rapass.cpp",

    "asmjit/x86/x86assembler.cpp",
    "asmjit/x86/x86builder.cpp",
    "asmjit/x86/x86compiler.cpp",
    "asmjit/x86/x86emithelper.cpp",
    "asmjit/x86/x86formatter.cpp",
    "asmjit/x86/x86func.cpp",
    "asmjit/x86/x86instdb.cpp",
    "asmjit/x86/x86instapi.cpp",
    "asmjit/x86/x86operand.cpp",
    "asmjit/x86/x86rapass.cpp",

    "asmjit/ujit/unicompiler_a64.cpp",
    "asmjit/ujit/unicompiler_x86.cpp",
    "asmjit/ujit/vecconsttable.cpp",
]

thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]
env_gdscript.Prepend(CPPPATH=[thirdparty_dir])

env_thirdparty = env_gdscript.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.Append(
    CPPDEFINES=[
        "ASMJIT_STATIC",
    ]
)

env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

env_gdscript.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build:
    env_gdscript.add_source_files(env.modules_sources, "./editor/*.cpp")

    SConscript("editor/script_templates/SCsub")

    # Those two modules are required for the language server protocol
    if env["module_jsonrpc_enabled"] and env["module_websocket_enabled"]:
        env_gdscript.add_source_files(env.modules_sources, "./language_server/*.cpp")
    else:
        # Using a define in the disabled case, to avoid having an extra define
        # in regular builds where all modules are enabled.
        env_gdscript.Append(CPPDEFINES=["GDSCRIPT_NO_LSP"])
        # Also needed in main env to unexpose --lsp-port option.
        env.Append(CPPDEFINES=["GDSCRIPT_NO_LSP"])


if env["tests"]:
    env_gdscript.Append(CPPDEFINES=["TESTS_ENABLED"])
    env_gdscript.add_source_files(env.modules_sources, "./tests/*.cpp")